      SUBROUTINE RDPLOT(CUNITS,XSCLP,YSCLP,DELTA)
C
C     Read plotting control parameters
C
      CHARACTER*10 CUNITS
      REAL XSCLP, YSCLP, DELTA
C
      INTEGER In, Io
      COMMON /IOUNIT/ In, Io
C
      READ (In,9005) XSCLP, YSCLP, DELTA
      WRITE (Io,9010) XSCLP, YSCLP, DELTA, CUNITS
C
      RETURN
C
 9005 FORMAT (8F10.0)
 9010 FORMAT (/,26X,'PLOT SCALING FACTOR FOR X (XSCLP) =',1P1E13.6,/,
     &        26X,'PLOT SCALING FACTOR FOR Y (YSCLP) =',1P1E13.6,/,26X,
     &        'CONTOUR INCREMENT (DELTA) =',1P1E13.6,1X,A10)
      END
